language: node_js
node_js:
  - "0.12"
before_install:
  - sudo apt-get install expect
  - curl https://install.meteor.com | /bin/sh
  - meteor update
deploy:
  provider: azure_web_apps
  on:
    all_branches: true